We have reached the last lesson in this Introduction to NumPy. In this last lesson we will see how NumPy does arithmetic operations on ndarrays. NumPy allows element-wise operations on ndarrays as well as matrix operations. In this lesson we will only be looking at element-wise operations on ndarrays. In order to do element-wise operations, NumPy sometimes uses something called Broadcasting. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

Let's start by doing element-wise addition, subtraction, multiplication, and division, between ndarrays. To do this, NumPy provides a functional approach, where we use functions such as np.add(), or by using arithmetic symbols, such as +, that resembles more how we write mathematical equations. Both forms will do the same operation, the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable. We'll explain more about this later in this lesson. Let's start by performing element-wise arithmetic operations on rank 1 ndarrays:

In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
print('x = ', x)
print('\n')
print('y = ', y)
print('\n')

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x+y)
print('add(x, y) = ', np.add(x, y))
print('\n')
print('X - y = ', x - y)
print('subtract(x, y) = ', np.subtract(x, y))
print('\n')
print('x * y = ', x * y)
print('multiply(x, y) = ', np.multiply(x, y))
print('\n')
print('x / y = ', x / y)
print('divide(x, y) = ', np.divide(x, y))
print('\n')

x =  [1 2 3 4]


y =  [ 5.5  6.5  7.5  8.5]


x + y =  [  6.5   8.5  10.5  12.5]
add(x, y) =  [  6.5   8.5  10.5  12.5]


X - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x, y) =  [-4.5 -4.5 -4.5 -4.5]


x * y =  [  5.5  13.   22.5  34. ]
multiply(x, y) =  [  5.5  13.   22.5  34. ]


x / y =  [ 0.18181818  0.30769231  0.4         0.47058824]
divide(x, y) =  [ 0.18181818  0.30769231  0.4         0.47058824]




We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [5]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print('X = \n', X)
print('\n')
print('Y = \n', Y)
print('\n')

# We pefrom basic element-wise operations using arithmetic symbols and functions 
print('X + Y = \n', X + Y)
print('add(X,Y) = \n', np.add(X,Y))
print('\n')
print('X - Y = \n', X - Y)
print('subtract(X,Y) = \n', np.subtract(X,Y))
print('\n')
print('X * Y = \n', X * Y)
print('multiply(X,Y) = \n', np.multiply(X,Y))
print('\n')
print('X / Y = \n', X / Y)
print('divide(X,Y) = \n', np.divide(X,Y))
print('\n')

X = 
 [[1 2]
 [3 4]]


Y = 
 [[ 5.5  6.5]
 [ 7.5  8.5]]


X + Y = 
 [[  6.5   8.5]
 [ 10.5  12.5]]
add(X,Y) = 
 [[  6.5   8.5]
 [ 10.5  12.5]]


X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]


X * Y = 
 [[  5.5  13. ]
 [ 22.5  34. ]]
multiply(X,Y) = 
 [[  5.5  13. ]
 [ 22.5  34. ]]


X / Y = 
 [[ 0.18181818  0.30769231]
 [ 0.4         0.47058824]]
divide(X,Y) = 
 [[ 0.18181818  0.30769231]
 [ 0.4         0.47058824]]




We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.

In [8]:
x = np.array([1,2,3,4])
print('x = ', x)
print('\n')

# We apply different mathematical functions to all elements of x
print('EXP(x) = ', np.exp(x))
print('\n')
print('SQRT(x) =', np.sqrt(x))
print('\n')
print('POW(x, 2) =', np.power(x, 2)) # We raise all elements to the power of 2
print('\n')

x =  [1 2 3 4]


EXP(x) =  [  2.71828183   7.3890561   20.08553692  54.59815003]


SQRT(x) = [ 1.          1.41421356  1.73205081  2.        ]


POW(x, 2) = [ 1  4  9 16]




Another great feature of NumPy is that it has a wide variety of statistical functions. Statistical functions provide us with statistical information about the elements in an ndarray. Let's see some examples:

In [9]:
X = np.array([[1,2], [3,4]])
print('X = \n', X)
print('\n')

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print('\n')
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print('\n')
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print('\n')
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print('\n')
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print('\n')
print('Maximum value of all elements in X:', X.min())
print('Maximum value of all elements in the columns of X:', X.min(axis=0))
print('Maximum value of all elements in the rows of X:', X.min(axis=1))
print('\n')

X = 
 [[1 2]
 [3 4]]


Average of all elements in X: 2.5
Average of all elements in the columns of X: [ 2.  3.]
Average of all elements in the rows of X: [ 1.5  3.5]


Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]


Standard Deviation of all elements in X: 1.11803398875
Standard Deviation of all elements in the columns of X: [ 1.  1.]
Standard Deviation of all elements in the rows of X: [ 0.5  0.5]


Median of all elements in X: 2.5
Median of all elements in the columns of X: [ 2.  3.]
Median of all elements in the rows of X: [ 1.5  3.5]


Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]


Maximum value of all elements in X: 1
Maximum value of all elements in the columns of X: [1 2]
Maximum value of all elements in the rows of X: [1 3]




Finally, let's see how NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [11]:
X = np.array([[1,2], [3,4]])
print('X = \n', X)
print('\n')

print('3 * X = \n', 3 * X)
print('\n')
print('3 + X = \n', 3 + X)
print('\n')
print('X - 3 = \n', X - 3)
print('\n')
print('X / 3 = \n', X / 3)

X = 
 [[1 2]
 [3 4]]


3 * X = 
 [[ 3  6]
 [ 9 12]]


3 + X = 
 [[4 5]
 [6 7]]


X - 3 = 
 [[-2 -1]
 [ 0  1]]


X / 3 = 
 [[ 0.33333333  0.66666667]
 [ 1.          1.33333333]]


Subject to certain constraints, Numpy can do the same for two ndarrays of different shapes, as we can see below.

In [12]:
x = np.array([1,2,3])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z = np.array([1,2,3]).reshape(3,1)
print('x = ', x)
print('\n')
print('Y = \n', Y)
print('\n')
print('Z = \n', Z)

print('x + Y = \n', x + Y)
print('\n')
print('Z + Y = \n', Z + Y)

x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]
x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
