Up to now we have seen how to make slices and select elements of an ndarray using indices. This is useful when we know the exact indices of the elements we want to select. However, there are many situations in which we don't know the indices of the elements we want to select. For example, suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us select elements using logical arguments instead of explicit indices. Let's see some examples:

In [1]:
import numpy as np

In [5]:
X = np.arange(25).reshape(5,5)
print('Original X = \n', X)
print('\n')

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X>10])
print('The elements in X that are less than or equal to 7:', X[X<=7])
print('The elements in X that are between 10 and 17:', X[(X>10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1
print('X = \n', X)
print('\n')

Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that are less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]
X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]




In addition to Boolean Indexing NumPy also allows for set operations. This useful when comparing ndarrays, for example, to find common elements between two ndarrays. Let's see some examples:

In [8]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('x = ', x)
print('\n')
print('y = ', y)
print('\n')

# We use se toperations to compare x and y:
print('The elements that are in both and x and y:', np.intersect1d(x, y))
print('The elements that are in x that are not in y:', np.setdiff1d(x, y))
print('All the elements of x and y:', np.union1d(x, y))
print('\n')

x =  [1 2 3 4 5]


y =  [6 7 2 8 4]


The elements that are in both and x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]




We can also sort ndarrays in NumPy. We will learn how to use the np.sort() function to sort rank 1 and rank 2 ndarrays in different ways. Like with other functions we saw before, the sort function can also be used as a method. However, there is a big difference on how the data is stored in memory in this case. When np.sort() is used as a function, it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted. However, when you use sort as a method, ndarray.sort() sorts the ndarray in place, meaning, that the original array will be changed to the sorted one. Let's see some examples:

In [10]:
x = np.random.randint(1, 11, size=(10, ))
print('Original x = ', x)
print('\n')

# We sort x and print sorted array using sort as a function
print('Sorted x (out of place):', np.sort(x))
print('\n')

# When we sort out of place the original array remains intact. To see this we print x again
print('x after sorting: ', x)
print('\n')

Original x =  [10  2  2  7  9  4  5  9  9  3]


Sorted x (out of place): [ 2  2  3  4  5  7  9  9  9 10]


x after sorting:  [10  2  2  7  9  4  5  9  9  3]




Notice that np.sort() sorts the array but, if the ndarray being sorted has repeated values, np.sort() leaves those values in the sorted array. However, if desired, we can sort only the unique elements in x by combining the sort function with the unique function. Let's see how we can sort the unique elements of x above:

In [12]:
print(np.sort(np.unique(x)))
print('\n')

[ 2  3  4  5  7  9 10]




Finally, let's see how we can sort ndarrays in place, by using sort as a method:

In [14]:
x = np.random.randint(1,11,size=(10,))
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print('x after sorting:', x)
print('\n')

Original x =  [ 7  5 10  1  2 10  4  7  1  3]
x after sorting: [ 1  1  2  3  4  5  7  7 10 10]




When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword. Let's see some examples:

In [16]:
X = np.random.randint(1,11, size=(5,5))
print('Original X = \n', X)
print('\n')

# We sort the columns of X and print the sorted array
print('X with sorted columns :\n', np.sort(X, axis=0))
print('\n')

# We sort the rows of X and print the sorted array
print('X with sorted rows :\n', np.sort(X, axis=1))
print('\n')

Original X = 
 [[ 1  6  1 10  9]
 [ 4  5  2  2  5]
 [ 2  6  6  8  2]
 [ 8  2  2  1  4]
 [ 4  6  7  6  6]]


X with sorted columns :
 [[ 1  2  1  1  2]
 [ 2  5  2  2  4]
 [ 4  6  2  6  5]
 [ 4  6  6  8  6]
 [ 8  6  7 10  9]]


X with sorted rows :
 [[ 1  1  6  9 10]
 [ 2  2  4  5  5]
 [ 2  2  6  6  8]
 [ 1  2  2  4  8]
 [ 4  6  6  6  7]]


