At the core of NumPy is the *ndarray*, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings. In many Machine Learning problems you will often find yourself using ndarrays in many different ways. For instance, you might use an ndarray to hold the pixel values of an image that will be fed into a Neural Network for image classification.

But before we can dive in and start using NumPy to create ndarrays we need to import it into Python. We can import packages into Python using the import command and it has become a convention to import NumPy as np. Therefore, you can import NumPy by typing the following command in your Jupyter notebook:

In [1]:
import numpy as np

There are several ways to create ndarrays in NumPy. In the following lessons we will see two ways to create ndarrays:
1. Using regular Python list
2. Using built-in Numpy functions

In this section, we will create ndarrays by providing Python lists to the NumPy *np.array()* function. This can create some confusion for beginners, but is important to remember that *np.array()* is NOT a class, it is just a function that returns an ndarray. We should note that for the purposes of clarity, the examples throughout these lessons will use small and simple ndarrays. Let's start by creating 1-Dimensional (1D) ndarrays.

In [2]:
# We create a 1D ndarray that contains only integers
x = np.array([1,2,3,4,5])

In [3]:
# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [4]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type int32


In [5]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type', x.dtype)

x =  ['Hello' 'World']


x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type <U5


In [6]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1,2,'World'])
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type', x.dtype)

x =  ['1' '2' 'World']


x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type <U11


In [7]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3], [4,5,6], [7,8,9], [11,12,13]])
print('Y = \n', Y)
print('\n')
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an objects of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an objects of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [8]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])
# We create a rank 1 ndarray that contains floats
y = np.array([1.0, 2.0, 3.0])
# We create a rank 1 ndarray that contains integers and floats
z = np.array([1,2.5, 4])
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [9]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype=np.int64)
print('x = ', x)
print('\n')
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]


The elements in x are of type: int64


In [10]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])
# We save x into the current directory as 
np.save('my_array', x)

The above saves the x ndarray into a file named my_array.npy. You can load the saved ndarray into a variable by using the *load()* function.

In [11]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')
print('y = ', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y =  [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32
