One great time-saving feature of NumPy is its ability to create ndarrays using built-in functions. These functions allow us to create certain kinds of ndarrays with just one line of code. Below we will see a few of the most useful built-in functions for creating ndarrays that you will come across when doing AI programming.

Let's start by creating an ndarray with a specified shape that is full of zeros. We can do this by using the *np.zeros()* function. The function *np.zeros(shape)* creates an ndarray full of zeros with the given shape. So, for example, if you wanted to create a rank 2 array with 3 rows and 4 columns, you will pass the shape to the function in the form of (rows, columns), as in the example below:

In [3]:
import numpy as np
# we create a 3 x 4 ndarray full of zeros
X = np.zeros((3,4))
print('X = \n', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [5]:
# We create a 3 x 2 ndarray full on ones
X = np.ones((3,2))
print('X = \n', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type', X.dtype)

X = 
 [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type float64


In [8]:
# We create a 2 x 3 ndarray full of fives
X = np.full((2,3), 5)
print('X = \n', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of:', X.dtype)

X = 
 [[5 5 5]
 [5 5 5]]


X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of: int32


In [9]:
# We create a 5 x 5 Identity matrix
X = np.eye(5)
print('X = \n', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [10]:
# Create a 4 x 4 diagonal matrix that contrains the numbers: 10, 20, 30 and 50
# on it main diagonal
X = np.diag([10, 20,30,50])
print('X = \n', X)
print('\n')

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]




In [11]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [0 1 2 3 4 5 6 7 8 9]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [12]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9
x = np.arange(4,10)
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [4 5 6 7 8 9]


x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [13]:
# We create a rank 1 ndarray that has evenly spaced integers 1 to 13 in steps of 3
x = np.arange(1,14,3)
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 1  4  7 10 13]


x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [14]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
x = np.linspace(0,25,10)
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [15]:
# We create a rand 1 ndarray that has 10 integers evenly spaced between 0 and 25
# with 25 excluded
x = np.linspace(0,25,10, endpoint=False)
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [16]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print('x = ', x)
print('\n')
# We reshape x into a 4 x 5 ndarray
x = np.reshape(x, (4,5))
print('x = ', x)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


x =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [17]:
# We create a rank 1 ndarray with sequential integers from 0 to 19 and 
# reshape it to a 4 x 5 array
Y = np.arange(20).reshape(4,5)
print('Y = \n', Y)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [18]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print('X = ', X)
print('\n')
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

X =  [[  0.   5.]
 [ 10.  15.]
 [ 20.  25.]
 [ 30.  35.]
 [ 40.  45.]]


x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [24]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0)
X = np.random.random((3,3))
print('X = ', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X =  [[ 0.97874387  0.63205602  0.39692972]
 [ 0.09820234  0.20656686  0.53675116]
 [ 0.82715091  0.2054758   0.32630799]]


X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [22]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15)
X = np.random.randint(4,15, size=(3,2))
print('X = ',X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X =  [[ 5  8]
 [14 12]
 [10  8]]


X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [26]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distributions
# with a mean of zero and a standard deviation of 0.1
X = np.random.normal(0, 0.1, size=(1000, 1000))
print('X = \n', X)
print('\n')
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X = 
 [[  7.15063890e-02   7.18903154e-02   7.82285633e-02 ...,  -1.71666115e-01
    1.31597709e-02  -5.51297404e-02]
 [ -4.18364146e-02   1.91688472e-02   1.03975809e-02 ...,   1.41534998e-02
    1.96885525e-01   2.22526095e-01]
 [ -1.03711571e-01   1.41261330e-01   4.35934434e-02 ...,   6.45868742e-02
   -1.31042368e-01  -5.50672947e-02]
 ..., 
 [  4.44931679e-03  -6.26314026e-02  -8.83413629e-02 ...,  -6.19710968e-03
   -3.51812558e-02  -1.23680340e-01]
 [ -1.35125059e-01  -9.97294501e-02   4.74720936e-02 ...,   3.61809928e-02
    1.29329977e-01   1.54640661e-02]
 [  3.34317941e-02   6.03375265e-02  -1.06669867e-01 ...,  -3.30282732e-02
    1.21853697e-04   9.66727907e-02]]


X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64
The elements in X have a mean of: -0.000146628867325
The maximum value in X is: 0.487794222491
The minimum value in X is: -0.459482369337
X has 500213 negative numbers
X has 499787 positive numb